Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'user/list'
  get 'user/new'
  post 'user/create'
  patch 'user/update'
  get 'user/list'
  get 'user/show'
  get 'user/edit'
  get 'user/delete'
  get 'user/update'

  get 'restaurant/list'
  get 'restaurant/new'
  post 'restaurant/create'
  patch 'restaurant/update'
  get 'restaurant/list'
  get 'restaurant/show'
  get 'restaurant/edit'
  get 'restaurant/delete'
  get 'restaurant/update'

  get 'comment/list'
  get 'comment/new'
  post 'comment/create'
  get 'comment/list'
  get 'comment/show'
  get 'comment/delete'

  get 'contact/list'
  get 'contact/new'
  post 'contact/create'
  patch 'contact/update'
  get 'contact/list'
  get 'contact/show'
  get 'contact/edit'
  get 'contact/delete'
  get 'contact/update'

  get 'price/list'
  get 'price/new'
  post 'price/create'
  get 'price/list'
  get 'price/delete'

  get 'schedule/list'
  get 'schedule/new'
  post 'schedule/create'
  patch 'schedule/update'
  get 'schedule/list'
  get 'schedule/show'
  get 'schedule/edit'
  get 'schedule/delete'
  get 'schedule/update'

  get 'photo/list'
  get 'photo/new'
  post 'photo/create'
  patch 'photo/update'
  get 'photo/list'
  get 'photo/show'
  get 'photo/edit'
  get 'photo/delete'
  get 'photo/update'
end
